import type { SiteConfig } from "./types.ts";

const open = { openMin: 9 * 60, closeMin: 16 * 60 };
const saturday = { openMin: 9 * 60, closeMin: 13 * 60 };

/**
 * Saltbush Dog Grooming, the sample client.
 * Its light theme replaces the firm defaults. Dark mode is off.
 */
export const saltbush = {
  id: "saltbush",
  businessName: "Saltbush Dog Grooming",
  storage: { key: "saltbush-booking-demo-v1", version: 1 },
  credit: "light",
  theme: {
    dark: false,
    light: {
      "--bg": "#f3eee6",
      "--card": "#fffcf7",
      "--fg": "#1c2824",
      "--muted": "#5c6b64",
      "--border": "#ddd2c3",
      "--soft": "#e7dfd2",
      "--primary": "#1b3f34",
      "--primary-fg": "#f6efe4",
      "--primary-hover": "#1b3f34",
      "--outline-hover": "transparent",
      "--ring": "#c4613a",
      "--ring-width": "3px",
      "--accent": "#c4613a",
      "--shadow": "0 16px 40px rgba(28, 40, 36, 0.08)",
      "--font-ui": 'Outfit, "Avenir Next", "Segoe UI", sans-serif',
      "--font-display": '"Bricolage Grotesque", "Bricolage Fallback", "Avenir Next", "Segoe UI", sans-serif',
      "--root-size": "17px",
      "--heading-weight": "700",
      "--heading-tracking": "-0.03em",
      "--h1-size": "clamp(2.25rem, 4.7vw, 3.9rem)",
      "--h1-weight": "750",
      "--h1-tracking": "-0.04em",
      "--h1-leading": "1.02",
      "--h1-wrap": "balance",
      "--h2-size": "clamp(1.6rem, 3vw, 2.1rem)",
      "--h2-leading": "1.05",
      "--h3-size": "1.25rem",
      "--h3-weight": "650",
      "--h3-tracking": "-0.02em",
      "--h3-leading": "1.15",
      "--price-weight": "700",
      "--price-tracking": "-0.03em",
      "--day-num-weight": "650",
      "--day-num-tracking": "-0.02em",
      "--lockup-height": "52px",
      "--lockup-height-small": "46px",
      "--body-size": "17px",
      "--body-leading": "1.5",
      "--lede-size": "1.125rem",
      "--lede-color": "#5c6b64",
      "--btn-size": "17px",
      "--btn-weight": "600",
      "--btn-leading": "1.5",
      "--btn-min-h": "48px",
      "--btn-pad": "10px 18px",
      "--card-pad": "18px",
      "--radius-card": "18px",
      "--radius-hero": "28px",
      "--radius-choice": "14px",
      "--radius-day": "14px",
      "--shell": "1080px",
      "--gutter": "16px",
      "--footer-bg": "#ebe4d8",
      "--banner-bg": "#2a241c",
      "--banner-fg": "#f6efe4",
      "--hero-bg": "#1b3f34",
      "--hero-fg": "#f6efe4",
      "--hero-border": "transparent",
      "--highlight": "#f3f7f4",
      "--highlight-accent": "#2f6a56",
      "--choice-border": "#2f6a56",
      "--slot-selected-bg": "#2f6a56",
      "--slot-selected-fg": "#ffffff",
      "--on-primary-muted": "#d5e4dc",
      "--taken-bg": "#e7e2da",
      "--taken-fg": "#3e4944",
      "--disabled-bg": "#efeae3",
      "--disabled-fg": "#3e4944",
      "--input-border": "#cfc3b2",
      "--input-bg": "#ffffff",
      "--link": "#1b3f34",
      "--link-offset": "auto",
      "--eyebrow-color": "#c4613a",
      "--eyebrow-size": "0.78rem",
      "--eyebrow-weight": "600",
      "--eyebrow-tracking": "0.14em",
      "--eyebrow-transform": "uppercase",
      "--toggle-fg": "#2f6a56",
      "--nav-demo-border": "#c4613a",
      "--pill-pending-bg": "#f4e4c4",
      "--pill-pending-fg": "#6d4b12",
      "--pill-confirmed-bg": "#d7eadf",
      "--pill-confirmed-fg": "#1d5c3d",
      "--pill-cancelled-bg": "#f0dcdc",
      "--pill-cancelled-fg": "#8d2f2f",
    },
  },
  headerArt: {
    src: "saltbush-v2-header-light.svg",
    dark: "saltbush-v2-header-dark.svg",
    width: 281,
    height: 80,
    alt: "Saltbush Dog Grooming",
  },
  heroArt: {
    src: "saltbush-v2-hero.svg",
    fallback: "saltbush-v2-hero-720x840.webp",
    width: 720,
    height: 840,
    alt: "Illustration: a fluffy cream dog in a rust bandana sitting on a sand dune by the sea, with saltbush shrubs and a low sun",
  },
  icons: [
    { rel: "icon", href: "saltbush-v2-favicon.svg", type: "image/svg+xml" },
    { rel: "apple-touch-icon", href: "saltbush-v2-apple-touch-180.png" },
  ],
  fontHref:
    "https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,600..800&family=Outfit:wght@400;500;600&display=swap",
  fallbackFonts: [
    {
      family: "Bricolage Fallback",
      local: ["Arial Bold", "Arial-BoldMT", "Liberation Sans Bold"],
      weight: "600 800",
      sizeAdjust: "92%",
      ascentOverride: "101%",
      descentOverride: "29.3%",
      lineGapOverride: "0%",
    },
  ],
  themeColor: "#2a241c",
  metaDescription:
    "Demo booking site by Crom Services for Saltbush Dog Grooming, an invented Australian salon. Sample data only. Emails are simulated.",
  titles: {
    home: "Saltbush Dog Grooming · Demo",
    book: "Book a visit · Saltbush demo",
    admin: "Demo desk · Saltbush",
    notFound: "Page not found · Saltbush demo",
  },
  banner: "Demo site by Crom Services. Not a real business. Sample data only. Emails are simulated.",
  nav: { home: "Home", book: "Book", admin: "Demo admin" },
  footerEmail: "cromservices@gmail.com",
  footerNote: "Portfolio demo. Saltbush Dog Grooming is not a real business.",
  schedule: {
    days: [null, open, open, open, open, open, saturday],
    horizonDays: 14,
    slotStepMinutes: 30,
    lines: [
      { label: "Monday to Friday", value: "9:00 am \u2013 4:00 pm" },
      { label: "Saturday", value: "9:00 am \u2013 1:00 pm" },
      { label: "Sunday", value: "Closed" },
    ],
  },
  services: [
    {
      id: "svc-bath",
      name: "Bath & brush",
      summary: "Warm wash, brush, and a tidy of ears and feet.",
      priceCents: 6500,
      durationMinutes: 60,
      active: true,
    },
    {
      id: "svc-groom",
      name: "Full groom",
      summary: "Bath, dry, and a clip shaped to the coat.",
      priceCents: 12000,
      durationMinutes: 90,
      active: true,
    },
    {
      id: "svc-puppy",
      name: "Puppy introduction",
      summary: "A short first visit for dogs under six months.",
      priceCents: 5500,
      durationMinutes: 45,
      active: true,
    },
    {
      id: "svc-nails",
      name: "Nail and paw tidy",
      summary: "Nails and a quick check of feet. No bath.",
      priceCents: 3000,
      durationMinutes: 30,
      active: true,
    },
    {
      id: "svc-deshed",
      name: "De-shed blow-out",
      summary: "A heavier brush-out for coats that are dropping.",
      priceCents: 9000,
      durationMinutes: 75,
      active: true,
    },
  ],
  extraFields: [
    {
      id: "dogName",
      label: "Dog's name",
      kind: "text",
      required: true,
      autoComplete: "off",
      pattern: "^[\\p{L}][\\p{L}\\p{M}'’.\\- ]{0,39}$",
      patternFlags: "u",
      messages: {
        required: "Enter the dog's name.",
        invalid: "Enter the dog's name.",
      },
    },
    {
      id: "dogSize",
      label: "Size",
      kind: "select",
      required: true,
      emptyLabel: "Choose a size",
      options: ["Small", "Medium", "Large", "Giant"],
      messages: {
        required: "Choose a size.",
        invalid: "Choose a size.",
      },
    },
  ],
  extras: { heading: "Dog", empty: "Not recorded", separator: " · " },
  sampleBookings: [
    {
      id: "bkg-mia",
      customerName: "Mia Tran",
      extras: { dogName: "Noodle", dogSize: "Small" },
      mobile: "0400 000 111",
      email: "mia.tran@example.com",
      serviceId: "svc-bath",
      notes: "Noodle is nervous of the dryer, towel finish please.",
      status: "confirmed",
      confirmationCode: "111111",
      minuteOfDay: 10 * 60 + 30,
      dayIndex: 0,
    },
    {
      id: "bkg-sam",
      customerName: "Sam Okafor",
      extras: { dogName: "Wattle", dogSize: "Medium" },
      mobile: "0400 000 222",
      email: "sam.okafor@example.com",
      serviceId: "svc-groom",
      notes: "Wattle's first full groom, keep it short and calm.",
      status: "pending",
      confirmationCode: "222222",
      minuteOfDay: 11 * 60,
      dayIndex: 1,
    },
    {
      id: "bkg-priya",
      customerName: "Priya Nair",
      extras: { dogName: "Biscuit", dogSize: "Large" },
      mobile: "0400 000 333",
      email: "priya.nair@example.com",
      serviceId: "svc-nails",
      notes: "",
      status: "cancelled",
      confirmationCode: "333333",
      minuteOfDay: 9 * 60 + 30,
      dayIndex: 2,
    },
  ],
  fields: {
    name: { label: "Name" },
    mobile: { label: "Mobile", hint: "An Australian mobile, such as 0412 345 678." },
    email: { label: "Email" },
    notes: { label: "Notes" },
  },
  loading: "Loading sample data…",
  emptyServices: "The sample menu is empty. Restore it from the demo desk.",
  home: {
    eyebrow: "Dog grooming · By appointment",
    headline: "A calm groom for dogs who would rather be at the beach.",
    lede: "Gentle baths, tidy clips and nail trims in a quiet studio, one dog at a time. Pick a service, choose an open time and you're booked in under a minute.",
    primaryCta: "Check open times",
    primaryHref: "/book?service=svc-bath",
    secondaryCta: "Demo desk",
    secondaryHref: "/admin",
    heroNote: "Quiet studio · one dog at a time",
    servicesHeading: "Services",
    servicesNote: "Prices in Australian dollars.",
    seeTimes: "See times for {name}",
    hoursHeading: "Hours",
    hoursNote: "Times are studio time. The calendar shows the next 14 days.",
    howHeading: "How a booking works",
    steps: [
      "Choose a service and an open time.",
      "Leave your name, the dog's name and size, an Australian mobile, and an email.",
      "Read the confirmation code on the sample email. Nothing is sent.",
      "The demo desk approves, moves, or cancels the request.",
    ],
    visitHeading: "The studio",
    visitBody: "12 Demonstration Lane. This address is fictional.",
  },
  book: {
    eyebrow: "Online booking",
    title: "Book a visit",
    intro:
      "Choose a service, then an open time in the next two weeks. Taken times stay visible and cannot be selected. Nothing on this page is emailed.",
    emailHeading: "Simulated confirmation email",
    emailIntro: "Read the code here. It is not sent to the address below.",
    emailKicker: "Simulated email · not sent",
    emailFrom: "Saltbush Dog Grooming <bookings@saltbush.example>",
    emailSubject: "Your sample confirmation code",
    emailHello: "Hello {customerName},",
    emailBody:
      "This message was not sent. It only exists on this demo page so you can confirm the request for {serviceName} for {dogName} ({dogSize}) on {when} ({price}, {duration}).",
    codeLabel: "Confirmation code",
    confirmLabel: "Code from the sample email",
    confirmHint: "Type the 6-digit code shown above.",
    confirmButton: "Confirm with code",
    confirmBusy: "Checking…",
    successEyebrow: "Sample code matched",
    successHeading: "Request lodged",
    successBody:
      "{customerName} is pending in the demo desk for {dogName} ({dogSize}), {serviceName} on {when}. No email was sent.",
    deskCta: "Open the demo desk",
    anotherCta: "Book another time",
    serviceLegend: "Service",
    timesHeading: "Open times",
    timesNote: "Studio hours, next 14 days. Taken slots stay on the calendar.",
    chooseService: "Choose a service to see times that fit.",
    closedDay: "The studio is closed this day.",
    noTimes: "No times left this day.",
    detailsHeading: "Your details",
    detailsNote:
      "Name, mobile, email, the dog's name and size, service, and time are required. Notes can be left blank.",
    formHint: "Demo only, use made-up details. Saved in this browser only.",
    submit: "Request this time",
    submitBusy: "Saving…",
    afterNote: "The code in the next step is shown on screen and is never emailed.",
    formLabel: "Booking details",
    confirmFormLabel: "Confirm the sample code",
    emailArticleLabel: "Simulated confirmation email",
    openLabel: "Open",
    takenLabel: "Taken",
  },
  admin: {
    eyebrow: "Demo · no login",
    title: "Demo desk",
    intro:
      "No login. This page is part of the public demo and only changes sample data in this browser. Approve, cancel, or move a booking, or edit the menu.",
  },
  notFound: {
    title: "That page is not on this demo.",
    body: "The sample site has a home page, a booking calendar, and a demo desk.",
    cta: "Back to the salon",
  },
} satisfies SiteConfig;

export const siteConfig = saltbush;
