import type { SiteConfig } from "../types.ts";

const weekday = { openMin: 10 * 60, closeMin: 17 * 60 };
const saturday = { openMin: 10 * 60, closeMin: 13 * 60 };

/**
 * A second sample, not the deployed site.
 * It leaves the theme unset, so the firm light skin and the firm dark skin apply.
 */
export const harbourPress = {
  id: "harbour-press",
  businessName: "Harbour Press",
  storage: { key: "harbour-press-booking-v1", version: 1 },
  credit: "system",
  fontHref: "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap",
  themeColor: "#f3f2ef",
  metaDescription:
    "Demo booking site by Crom Services for Harbour Press, an invented Australian print studio. Sample data only. Emails are simulated.",
  titles: {
    home: "Harbour Press · Demo",
    book: "Book a slot · Harbour Press demo",
    admin: "Demo desk · Harbour Press",
    notFound: "Page not found · Harbour Press demo",
  },
  banner: "Demo site by Crom Services. Not a real business. Sample data only. Emails are simulated.",
  nav: { home: "Home", book: "Book", admin: "Demo admin" },
  footerEmail: "cromservices@gmail.com",
  footerNote: "Portfolio demo. Harbour Press is not a real business.",
  schedule: {
    days: [null, weekday, weekday, weekday, weekday, weekday, saturday],
    horizonDays: 14,
    slotStepMinutes: 30,
    lines: [
      { label: "Monday to Friday", value: "10:00 am \u2013 5:00 pm" },
      { label: "Saturday", value: "10:00 am \u2013 1:00 pm" },
      { label: "Sunday", value: "Closed" },
    ],
  },
  services: [
    {
      id: "svc-cards",
      name: "Calling cards",
      summary: "A short run of cotton cards, set and printed while you wait.",
      priceCents: 4800,
      durationMinutes: 45,
      active: true,
    },
    {
      id: "svc-poster",
      name: "A2 poster",
      summary: "One poster, proofed on the bench and printed in the afternoon.",
      priceCents: 9000,
      durationMinutes: 60,
      active: true,
    },
    {
      id: "svc-programme",
      name: "Folded programme",
      summary: "A small folded piece for a recital, dinner, or talk.",
      priceCents: 12000,
      durationMinutes: 75,
      active: true,
    },
  ],
  extraFields: [
    {
      id: "jobName",
      label: "Job name",
      kind: "text",
      required: true,
      autoComplete: "off",
      pattern: "^[\\p{L}\\p{N}][\\p{L}\\p{N}\\p{M}'’\\-. ]{0,59}$",
      patternFlags: "u",
      messages: {
        required: "Enter a job name.",
        invalid: "Enter a job name.",
      },
    },
    {
      id: "stock",
      label: "Stock",
      kind: "select",
      required: true,
      emptyLabel: "Choose a stock",
      options: ["Cotton", "Recycled", "Bright"],
      messages: {
        required: "Choose a stock.",
        invalid: "Choose a stock.",
      },
    },
  ],
  extras: { heading: "Job", empty: "Not recorded", separator: " · " },
  sampleBookings: [
    {
      id: "bkg-ada",
      customerName: "Ada Okonkwo",
      extras: { jobName: "Spring recital", stock: "Cotton" },
      mobile: "0400 111 222",
      email: "ada.okonkwo@example.com",
      serviceId: "svc-programme",
      notes: "Keep the margins wide.",
      status: "confirmed",
      confirmationCode: "121212",
      minuteOfDay: 10 * 60 + 30,
      dayIndex: 0,
    },
    {
      id: "bkg-leo",
      customerName: "Leo March",
      extras: { jobName: "Market poster", stock: "Recycled" },
      mobile: "0400 222 333",
      email: "leo.march@example.com",
      serviceId: "svc-poster",
      notes: "",
      status: "pending",
      confirmationCode: "343434",
      minuteOfDay: 13 * 60,
      dayIndex: 1,
    },
  ],
  fields: {
    name: { label: "Name" },
    mobile: { label: "Mobile", hint: "An Australian mobile, such as 0412 345 678." },
    email: { label: "Email" },
    notes: { label: "Notes" },
  },
  loading: "Loading sample data…",
  emptyServices: "The sample menu is empty. Restore it from the demo desk.",
  home: {
    eyebrow: "Letterpress · By appointment",
    headline: "A quiet press for small jobs that need a careful print.",
    lede: "Cards, posters, and short programmes, one job on the press at a time. Pick a service, choose an open slot, and the request stays in this browser.",
    primaryCta: "Check open slots",
    primaryHref: "/book?service=svc-cards",
    secondaryCta: "Demo desk",
    secondaryHref: "/admin",
    heroNote: "One job on the press at a time",
    servicesHeading: "Services",
    servicesNote: "Prices in Australian dollars.",
    seeTimes: "See times for {name}",
    hoursHeading: "Hours",
    hoursNote: "Times are studio time. The calendar shows the next 14 days.",
    howHeading: "How a booking works",
    steps: [
      "Choose a service and an open slot.",
      "Leave your name, a job name, the paper stock, an Australian mobile, and an email.",
      "Read the confirmation code on the sample email. Nothing is sent.",
      "The demo desk approves, moves, or cancels the request.",
    ],
    visitHeading: "The press",
    visitBody: "This studio is fictional. Harbour Press is not a real business.",
  },
  book: {
    eyebrow: "Online booking",
    title: "Book a slot",
    intro:
      "Choose a service, then an open slot in the next two weeks. Taken times stay visible and cannot be selected. Nothing on this page is emailed.",
    emailHeading: "Simulated confirmation email",
    emailIntro: "Read the code here. It is not sent to the address below.",
    emailKicker: "Simulated email · not sent",
    emailFrom: "Harbour Press <bookings@harbourpress.example>",
    emailSubject: "Your sample confirmation code",
    emailHello: "Hello {customerName},",
    emailBody:
      "This message was not sent. It only exists on this demo page so you can confirm the request for {serviceName} ({jobName}, {stock}) on {when} ({price}, {duration}).",
    codeLabel: "Confirmation code",
    confirmLabel: "Code from the sample email",
    confirmHint: "Type the 6-digit code shown above.",
    confirmButton: "Confirm with code",
    confirmBusy: "Checking…",
    successEyebrow: "Sample code matched",
    successHeading: "Request lodged",
    successBody:
      "{customerName} is pending in the demo desk for {jobName} ({stock}), {serviceName} on {when}. No email was sent.",
    deskCta: "Open the demo desk",
    anotherCta: "Book another time",
    serviceLegend: "Service",
    timesHeading: "Open times",
    timesNote: "Studio hours, next 14 days. Taken slots stay on the calendar.",
    chooseService: "Choose a service to see times that fit.",
    closedDay: "The studio is closed this day.",
    noTimes: "No times left this day.",
    detailsHeading: "Your details",
    detailsNote: "Name, mobile, email, the job name, stock, service, and time are required. Notes can be left blank.",
    formHint: "Demo only, use made-up details. Saved in this browser only.",
    submit: "Request this time",
    submitBusy: "Saving…",
    afterNote: "The code in the next step is shown on screen and is never emailed.",
    formLabel: "Booking details",
    confirmFormLabel: "Confirm the sample code",
    emailArticleLabel: "Simulated confirmation email",
    openLabel: "Open",
    takenLabel: "Taken",
  },
  admin: {
    eyebrow: "Demo · no login",
    title: "Demo desk",
    intro:
      "No login. This page is part of the public demo and only changes sample data in this browser. Approve, cancel, or move a booking, or edit the menu.",
  },
  notFound: {
    title: "That page is not on this demo.",
    body: "The sample site has a home page, a booking calendar, and a demo desk.",
    cta: "Back to the press",
  },
} satisfies SiteConfig;

export const siteConfig = harbourPress;
